# Generated by Django 3.0.6 on 2020-05-21 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourcesql', models.TextField()),
                ('targetsql', models.TextField()),
                ('keycolumns', models.TextField(default='All')),
                ('sourcedbid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourcedb', to='connection.Connection')),
                ('targetdbid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targetdb', to='connection.Connection')),
            ],
        ),
    ]
