# Generated by Django 3.0.6 on 2020-05-21 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0001_initial'),
        ('testcase', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestCases',
            new_name='TestCase',
        ),
    ]
