# Generated by Django 3.0.6 on 2020-05-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0002_auto_20200521_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='tcname',
            field=models.CharField(default='abc', max_length=50),
            preserve_default=False,
        ),
    ]
