# Generated by Django 3.0.6 on 2020-05-26 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0003_testcase_tcname'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, max_length=200)),
                ('execution_start', models.DateTimeField(auto_now_add=True)),
                ('execution_end', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testcase.TestCase')),
            ],
        ),
    ]
