# Generated by Django 3.0.6 on 2020-05-26 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0004_testcaseresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcaseresult',
            old_name='status',
            new_name='testcase',
        ),
    ]
