# Generated by Django 3.1.1 on 2020-09-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0005_auto_20200526_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcaseresult',
            options={'ordering': ['-execution_end']},
        ),
    ]
