# Generated by Django 5.1.4 on 2024-12-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DbConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("dbname", models.CharField(max_length=200)),
                ("hostname", models.CharField(max_length=200)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("portno", models.IntegerField()),
                ("schema_name", models.CharField(blank=True, max_length=100)),
                ("create_dt", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "DB Connection",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="DbType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dbname", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "DB Type",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "project_slug",
                    models.SlugField(blank=True, max_length=100, null=True),
                ),
                ("project_code", models.CharField(max_length=6)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_date"],
            },
        ),
    ]
