# Generated by Django 5.1.4 on 2024-12-25 16:11
import datetime

from django.db import migrations


def create_through_relations(apps,schema_editor):
    Project = apps.get_model('project','Project')
    ProjectMember = apps.get_model('project','ProjectMember')
    for project in Project.objects.all():
        for member in project.members.all():
            ProjectMember(
                project = project,
                user = member,
                date_joined = datetime.datetime.now()
            ).save()


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_projectmember"),
    ]

    operations = [
        migrations.RunPython(create_through_relations, reverse_code=migrations.RunPython.noop),
]
