# Generated by Django 5.1.4 on 2024-12-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_auto_20241225_2141"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="members",
        ),
    ]
