# Generated by Django 5.1.4 on 2024-12-25 16:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_remove_project_members"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="projects",
                through="project.ProjectMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
