# Generated by Django 5.1.4 on 2024-12-26 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_project_members"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dbconnection",
            old_name="create_dt",
            new_name="created_dt",
        ),
    ]
