# Generated by Django 5.1.4 on 2024-12-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_rename_create_dt_dbconnection_created_dt"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmember",
            name="role",
            field=models.CharField(
                choices=[("member", "Member"), ("admin", "Admin"), ("guest", "Guest")],
                default="member",
                max_length=50,
            ),
        ),
    ]
