# Generated by Django 5.1.4 on 2024-12-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0008_projectmember_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dbconnection",
            name="dbname",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="dbconnection",
            name="hostname",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="dbconnection",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="dbconnection",
            name="password",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="dbconnection",
            name="schema_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="dbconnection",
            name="username",
            field=models.CharField(max_length=255),
        ),
    ]
