# Generated by Django 5.1.4 on 2024-12-31 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0009_alter_dbconnection_dbname_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectmember",
            options={"ordering": ["-date_joined"]},
        ),
    ]
