# Generated by Django 3.0.6 on 2020-05-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dbtype', models.CharField(choices=[('MySQL', 'MySQL'), ('PgSQL', 'PostGres'), ('MSSQL', 'MS SQL Server')], max_length=50)),
                ('dbname', models.CharField(max_length=200)),
                ('hostname', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('portno', models.IntegerField()),
            ],
        ),
    ]
