# Generated by Django 5.0.1 on 2024-10-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DbConnection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("dbname", models.CharField(max_length=200)),
                ("hostname", models.CharField(max_length=200)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("portno", models.IntegerField()),
                ("schema_name", models.CharField(blank=True, max_length=100)),
                ("create_dt", models.DateTimeField(auto_now=True)),
                ("warehouse_name", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "DB Connection",
            },
        ),
        migrations.CreateModel(
            name="DbType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dbname", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "DB Type",
            },
        ),
    ]
