# Generated by Django 5.0 on 2024-01-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                (
                    "dbtype",
                    models.CharField(
                        choices=[("MySQL", "MySQL"), ("Snowflake", "Snowflake"), ("MSSQL", "MS SQL Server")],
                        max_length=50,
                    ),
                ),
                ("dbname", models.CharField(max_length=200)),
                ("hostname", models.CharField(max_length=200)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("portno", models.IntegerField()),
                ("warehouse_name", models.CharField(max_length=100)),
                ("schema_name", models.CharField(max_length=100)),
            ],
        ),
    ]
