# Generated by Django 5.0.1 on 2024-10-30 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("connection", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dbconnection",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="connection", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="dbconnection",
            name="dbtype",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="dbtype", to="connection.dbtype"
            ),
        ),
    ]
