# Generated by Django 5.0 on 2024-01-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connection", "0002_connection_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connection",
            name="warehouse_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
