# Generated by Django 5.0 on 2024-01-19 13:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("connection", "0003_alter_connection_warehouse_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Connection",
            new_name="DbConnection",
        ),
    ]
