# Generated by Django 5.0 on 2024-01-21 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connection", "0004_rename_connection_dbconnection"),
    ]

    operations = [
        migrations.CreateModel(
            name="DbType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dbname", models.CharField(max_length=50)),
                ("create_dt", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="dbconnection",
            name="create_dt",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="dbconnection",
            name="dbtype",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="dbtype", to="connection.dbtype"
            ),
        ),
    ]
