# Generated by Django 5.0.1 on 2024-03-28 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("connection", "0007_remove_dbtype_create_dt_dbtype_created_dt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dbtype",
            name="created_dt",
        ),
    ]
