# Generated by Django 5.0.1 on 2024-10-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connection", "0008_remove_dbtype_created_dt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dbconnection",
            name="schema_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
