# Generated by Django 5.1.4 on 2024-12-24 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import testplan.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project", "0002_initial"),
        ("testplan", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="created_by",
            field=models.ForeignKey(
                on_delete=models.SET(testplan.models.get_deleted_user_instance),
                related_name="testcase_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="testcase",
            name="modified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET(testplan.models.get_deleted_user_instance),
                related_name="testcase_modified_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="testcase",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project_testcases",
                to="project.project",
            ),
        ),
        migrations.AddField(
            model_name="testcase",
            name="sourcedb",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sourcedb",
                to="project.dbconnection",
            ),
        ),
        migrations.AddField(
            model_name="testcase",
            name="targetdb",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="targetdb",
                to="project.dbconnection",
            ),
        ),
        migrations.AddField(
            model_name="testrun",
            name="created_by",
            field=models.ForeignKey(
                on_delete=models.SET(testplan.models.get_deleted_user_instance),
                related_name="testrun_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="testrun",
            name="modified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET(testplan.models.get_deleted_user_instance),
                related_name="testrun_modified_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="testrun",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project_testruns",
                to="project.project",
            ),
        ),
        migrations.AddField(
            model_name="testruntestcase",
            name="testcase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="testplan.testcase"
            ),
        ),
        migrations.AddField(
            model_name="testruntestcase",
            name="testcase_status",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="testplan.testcasestatus",
            ),
        ),
        migrations.AddField(
            model_name="testruntestcase",
            name="testrun",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="testplan.testrun"
            ),
        ),
        migrations.AddField(
            model_name="testrun",
            name="testcases",
            field=models.ManyToManyField(
                blank=True, through="testplan.TestRunTestCase", to="testplan.testcase"
            ),
        ),
        migrations.AddField(
            model_name="testruntestcasehistory",
            name="testcase",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history_test_run",
                to="testplan.testcase",
            ),
        ),
        migrations.AddField(
            model_name="testruntestcasehistory",
            name="testcase_run_status",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="testplan.testcasestatus",
            ),
        ),
        migrations.AddField(
            model_name="testruntestcasehistory",
            name="testrun",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history_test_run",
                to="testplan.testrun",
            ),
        ),
        migrations.AddField(
            model_name="testruntestcasehistory",
            name="testrun_testcase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="testrun_testcase_history",
                to="testplan.testruntestcase",
            ),
        ),
        migrations.AddField(
            model_name="testruntestcasehistory",
            name="triggered_by",
            field=models.ForeignKey(
                on_delete=models.SET(testplan.models.get_deleted_user_instance),
                related_name="testrun_history_triggered_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
