# Generated by Django 5.0.1 on 2024-02-22 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testplan", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="modules", to="testplan.project"
            ),
        ),
    ]
