# Generated by Django 5.0.1 on 2024-02-29 03:57

import django.db.models.deletion
import testplan.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connection", "0006_alter_dbconnection_options_alter_dbtype_options"),
        ("testplan", "0002_alter_module_project"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TestCase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tcname", models.CharField(max_length=50)),
                ("sourcesql", models.TextField()),
                ("targetsql", models.TextField()),
                ("keycolumns", models.TextField(default="All")),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=models.SET(testplan.models.get_deleted_user_instance),
                        related_name="testcase_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        on_delete=models.SET(testplan.models.get_deleted_user_instance),
                        related_name="testcase_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="module_testcases",
                        to="testplan.module",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_testcases",
                        to="testplan.project",
                    ),
                ),
                (
                    "sourcedbid",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sourcedb",
                        to="connection.dbconnection",
                    ),
                ),
                (
                    "targetdbid",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="targetdb",
                        to="connection.dbconnection",
                    ),
                ),
            ],
        ),
    ]
