# Generated by Django 5.0.1 on 2024-12-21 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testplan", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testcase",
            name="module",
        ),
        migrations.DeleteModel(
            name="Module",
        ),
    ]
