# Generated by Django 5.1.4 on 2024-12-30 10:38

from django.db import migrations


def set_folder_to_testcase(apps, schema_editor):
    Project = apps.get_model("project", "Project")
    TestCaseFolder = apps.get_model("testplan", "TestCaseFolder")

    projects = Project.objects.all()  # Get All Projects

    for project in projects:
        """
        for each project, create a testcasefolder then update the testcases with the created testcasefolder
        """
        testcasefolder = TestCaseFolder.objects.create(
            created_by=project.owner, project=project, name="root"
        )
        testcasefolder.save()
        testcases = project.project_testcases.all()
        testcases.update(folder=testcasefolder)


class Migration(migrations.Migration):

    dependencies = [
        (
            "testplan",
            "0003_alter_testruntestcasehistory_options_testcasefolder_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            set_folder_to_testcase, reverse_code=migrations.RunPython.noop
        ),
    ]
