# Generated by Django 5.1.4 on 2024-12-30 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testplan", "0004_auto_20241230_1608"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcase",
            name="folder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folder_testcases",
                to="testplan.testcasefolder",
            ),
        ),
    ]
