# Generated by Django 5.0.1 on 2024-02-29 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testplan", "0004_alter_testcase_modified_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testcase",
            old_name="sourcedbid",
            new_name="sourcedb",
        ),
        migrations.RenameField(
            model_name="testcase",
            old_name="targetdbid",
            new_name="targetdb",
        ),
    ]
