# Generated by Django 5.1.4 on 2025-01-08 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testplan", "0006_alter_testcasefolder_project"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testcase",
            options={"ordering": ["-id"]},
        ),
    ]
