# Generated by Django 5.0.1 on 2024-03-28 02:29

import django.db.models.deletion
import testplan.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testplan", "0006_alter_module_modified_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TestCaseStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status_value", models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name="testcase",
            old_name="create_date",
            new_name="created_date",
        ),
        migrations.CreateModel(
            name="TestRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("closed_date", models.DateField(null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=models.SET(testplan.models.get_deleted_user_instance),
                        related_name="testrun_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(testplan.models.get_deleted_user_instance),
                        related_name="testrun_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_testruns",
                        to="testplan.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestRunCases",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("executed_date", models.DateTimeField(null=True)),
                (
                    "testcase_status",
                    models.ForeignKey(
                        default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to="testplan.testcasestatus"
                    ),
                ),
                ("testcases", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="testplan.testcase")),
                ("testrun", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="testplan.testrun")),
            ],
        ),
        migrations.AddField(
            model_name="testrun",
            name="testcases",
            field=models.ManyToManyField(through="testplan.TestRunCases", to="testplan.testcase"),
        ),
    ]
