# Generated by Django 5.0.1 on 2024-04-11 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testplan", "0008_alter_testrun_testcases"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestRunCasesHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("execution_start", models.DateTimeField(null=True)),
                ("execution_end", models.DateTimeField(null=True)),
                ("task_id", models.CharField(max_length=255)),
                (
                    "testcase_status",
                    models.ForeignKey(
                        default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to="testplan.testcasestatus"
                    ),
                ),
                (
                    "testrun_testcase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testrun_case_history",
                        to="testplan.testruncases",
                    ),
                ),
            ],
            options={
                "ordering": ["-execution_end"],
            },
        ),
    ]
