# Generated by Django 5.0.1 on 2024-04-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testplan", "0009_testruncaseshistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="testruncaseshistory",
            name="comments",
            field=models.TextField(blank=True),
        ),
    ]
