# Generated by Django 5.0.1 on 2024-10-27 17:24

import testplan.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testplan", "0011_rename_testcase_status_testruncaseshistory_run_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testruncases",
            name="executed_date",
        ),
        migrations.AddField(
            model_name="testruncaseshistory",
            name="triggered_by",
            field=models.ForeignKey(
                default=2,
                on_delete=models.SET(testplan.models.get_deleted_user_instance),
                related_name="testrun_history_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
